### ISSUE TITLE
rostest error

### ISSUE THREAD

**Issue by mkreddy477** [carla-simulator/ros-bridge#10]
I ran `rostest carla_ros_bridge ros_bridge_client.test`
Following is the error :
INFO] [1544617437.502630]: Trying to connect to localhost:2000
[INFO] [1544617437.504989]: Connected
[INFO] [1544617437.507103]: Starting Episode --> 0
[INFO] [1544617437.512320]: Adding sensor camera_front
[INFO] [1544617437.514650]: Adding sensor camera_depth
[INFO] [1544617438.434262]: Exiting Bridge
Traceback (most recent call last):
raceback (most recent call last):
  File "/home/aa/ros/catkin_ws_for_carla/src/carla_ros_bridge/src/carla_ros_bridge/client.py", line 42, in <module>
    main()
  File "/home/aa/ros/catkin_ws_for_carla/src/carla_ros_bridge/src/carla_ros_bridge/client.py", line 38, in main
    carla_ros_bridge.run()
  File "/home/aa/ros/catkin_ws_for_carla/src/carla_ros_bridge/src/carla_ros_bridge/bridge.py", line 143, in run
    map_handler = MapHandler(scene.map_name)
  File "/home/aa/ros/catkin_ws_for_carla/src/carla_ros_bridge/src/carla_ros_bridge/map.py", line 20, in __init__
    self.carla_map = CarlaMap(map_name)
TypeError: __init__() takes exactly 4 arguments (2 given)
[INFO] [1544617438.437316]: Shutdown requested
[Testcase: testtestTopics] ... ERROR!
ERROR: max time [20.0s] allotted for test [testTopics] of type [rostest/publishtest]
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rostest/runner.py", line 148, in fn
    self.test_parent.run_test(test)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rostest/rostest_parent.py", line 132, in run_test
    return self.runner.run_test(test)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/launch.py", line 689, in run_test
    (test.time_limit, test.test_name, test.package, test.type))
--------------------------------------------------------------------------------

[ROSTEST]-----------------------------------------------------------------------

SUMMARY
 * RESULT: FAIL
 * TESTS: 0
 * ERRORS: 1
 * FAILURES: 0

I am using ROS melodic as I am using Debian 9 machine.

Is there a work around for this?

Thanks in advance

**Comment by danil-tolkachev** [comment]
Hi @mkreddy477 
Which version of CARLA do you want to use?
- For 0.9.* use current master branch and look at issue #12 
- For 0.8.4 it needs to roll back ros-bridge.
