### ISSUE TITLE
'Actor' object has no attribute 'attributes'

### ISSUE THREAD

**Issue by anshulpaigwar** [carla-simulator/ros-bridge#12]
I am  having an error with rostest for new ros_bridge for carla_0.91

```
rostest carla_ros_bridge ros_bridge_client.test
... logging to /home/anshul/.ros/log/rostest-encre-454.log
[ROSUNIT] Outputting test results to /home/anshul/.ros/test_results/carla_ros_bridge/rostest-test_ros_bridge_client.xml
[INFO] [1545042396.298388, 0.000000]: Trying to connect to localhost:2000
[INFO] [1545042396.345882, 0.000000]: Connected
Traceback (most recent call last):
  File "/home/anshul/enable-s3/catkin_ws_carla/src/ros-bridge/src/carla_ros_bridge/bridge.py", line 155, in _carla_time_tick
    self.update()
  File "/home/anshul/enable-s3/catkin_ws_carla/src/ros-bridge/src/carla_ros_bridge/parent.py", line 156, in update
    self._create_new_children()
  File "/home/anshul/enable-s3/catkin_ws_carla/src/ros-bridge/src/carla_ros_bridge/parent.py", line 107, in _create_new_children
    carla_actor=actor, parent=self)
  File "/home/anshul/enable-s3/catkin_ws_carla/src/ros-bridge/src/carla_ros_bridge/spectator.py", line 40, in __init__
    append_role_name_topic_postfix=append_role_name_topic_postfix)  # pylint: disable=line-too-long
  File "/home/anshul/enable-s3/catkin_ws_carla/src/ros-bridge/src/carla_ros_bridge/actor.py", line 46, in __init__
    if carla_actor.attributes.has_key('role_name'):
AttributeError: 'Actor' object has no attribute 'attributes'
[INFO] [1545042405.890883, 0.000000]: Shutdown requested
[Testcase: testtestTopics] ... ok

[ROSTEST]-----------------------------------------------------------------------

[carla_ros_bridge.rosunit-testTopics/test_publish][FAILURE]---------------------
Timed out (10s) of /clock publication.
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/opt/ros/kinetic/share/rostest/nodes/publishtest", line 117, in test_publish
    self.fail('Timed out (10s) of /clock publication.')
  File "/usr/lib/python2.7/unittest/case.py", line 410, in fail
    raise self.failureException(msg)
--------------------------------------------------------------------------------


SUMMARY
 * RESULT: FAIL
 * TESTS: 1
 * ERRORS: 0
 * FAILURES: 1

```

**Comment by danil-tolkachev** [comment]
Changes for this bridge was pushed after 0.9.1 release. It needs fresh build of CARLA.

If you don't want rebuild CARLA (as me) you can find build artifacts for master branch here: http://158.109.9.218:8080/blue/organizations/jenkins/carla/branches

@nsubiron I hope I do not reveal any secrets by publishing this link.
