### ISSUE TITLE
AttributeError: 'World' object has no attribute 'get_snapshot

### ISSUE THREAD

**Issue by yzl96** [carla-simulator/ros-bridge#153]
roslaunch carla_ros_bridge carla_ros_bridge.launch

The error log is below:

Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/yzl/ros/carla/catkin_ws/src/ros-bridge-master/carla_ros_bridge/src/carla_ros_bridge/bridge.py", line 159, in _synchronous_mode_update
    world_snapshot = self.carla_world.get_snapshot()
AttributeError: 'World' object has no attribute 'get_snapshot'

**Comment by javieryu** [comment]
Solved at #150. Use the nightly release for CARLA.
