### ISSUE TITLE
ValueError: cannot reshape array, lidar misaligned

### ISSUE THREAD

**Issue by konradst** [carla-simulator/ros-bridge#335]
Hello,
I'm trying to `roslaunch carla_ros_bridge carla_ros_bridge_with_example_ego_vehicle.launch` and get spammed by sensor/lidar error. Camera and odometer work fine. Actually, on second look lidar also looks okay (excuse my initial panic, edited). I've tried the following setup:
Ubuntu Bionic
Python 2.7
Unreal: **4.24** (branch from source)
Carla: **0.9.9.4, 0.9.9** (branches from source)
ROS: **Melodic** (from apt)
ros bridge: **master** (branch from source)
pygame installed with pip (**1.9.6** because version from apt crashed)

I use rviz so I haven't been able to use noetic or python3 yet to even test if it would work properly.

The errors I'm getting:
```
ValueError: cannot reshape array of size 46053 into shape (11513,4)
Traceback (most recent call last):
  File "/home/konrad/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/sensor.py", line 105, in _callback_sensor_data
    self.sensor_data_updated(carla_sensor_data)
  File "/home/konrad/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/lidar.py", line 66, in sensor_data_updated
    lidar_data, (int(lidar_data.shape[0] / 4), 4))
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 232, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 46050 into shape (11512,4)
Traceback (most recent call last):
  File "/home/konrad/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/sensor.py", line 105, in _callback_sensor_data
    self.sensor_data_updated(carla_sensor_data)
  File "/home/konrad/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/lidar.py", line 66, in sensor_data_updated
    lidar_data, (int(lidar_data.shape[0] / 4), 4))
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 232, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 46074 into shape (11518,4)
Traceback (most recent call last):
  File "/home/konrad/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/sensor.py", line 105, in _callback_sensor_data
    self.sensor_data_updated(carla_sensor_data)
  File "/home/konrad/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/lidar.py", line 66, in sensor_data_updated
    lidar_data, (int(lidar_data.shape[0] / 4), 4))
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 232, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 46029 into shape (11507,4)
Traceback (most recent call last):
  File "/home/konrad/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/sensor.py", line 105, in _callback_sensor_data
    self.sensor_data_updated(carla_sensor_data)
  File "/home/konrad/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/lidar.py", line 66, in sensor_data_updated
    lidar_data, (int(lidar_data.shape[0] / 4), 4))
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 232, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 46038 into shape (11509,4)
Traceback (most recent call last):
  File "/home/konrad/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/sensor.py", line 105, in _callback_sensor_data
    self.sensor_data_updated(carla_sensor_data)
  File "/home/konrad/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/lidar.py", line 66, in sensor_data_updated
    lidar_data, (int(lidar_data.shape[0] / 4), 4))
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 232, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 46011 into shape (11502,4)
Traceback (most recent call last):
  File "/home/konrad/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/sensor.py", line 105, in _callback_sensor_data
    self.sensor_data_updated(carla_sensor_data)
  File "/home/konrad/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/lidar.py", line 66, in sensor_data_updated
    lidar_data, (int(lidar_data.shape[0] / 4), 4))
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 232, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 46011 into shape (11502,4)
Traceback (most recent call last):
  File "/home/konrad/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/sensor.py", line 105, in _callback_sensor_data
    self.sensor_data_updated(carla_sensor_data)
  File "/home/konrad/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/lidar.py", line 66, in sensor_data_updated
    lidar_data, (int(lidar_data.shape[0] / 4), 4))
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 232, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 45969 into shape (11492,4)
Traceback (most recent call last):
  File "/home/konrad/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/sensor.py", line 105, in _callback_sensor_data
    self.sensor_data_updated(carla_sensor_data)
  File "/home/konrad/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/lidar.py", line 66, in sensor_data_updated
    lidar_data, (int(lidar_data.shape[0] / 4), 4))
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 232, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 45969 into shape (11492,4)
^CTraceback (most recent call last):
  File "/home/konrad/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/sensor.py", line 105, in _callback_sensor_data
    self.sensor_data_updated(carla_sensor_data)
  File "/home/konrad/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/lidar.py", line 66, in sensor_data_updated
    lidar_data, (int(lidar_data.shape[0] / 4), 4))
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 232, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 45969 into shape (11492,4)
```
I think I might have some incompatible library installed (although I wonder why a lib would differ so much in public methods) but I'm quite confused which one of the many prerequisites may be wrong. Or is it a known issue?

**Comment by fpasch** [comment]
This is most likely related to CARLA 0.9.9.4 not containing https://github.com/carla-simulator/carla/pull/2997
Please test with the latest master.

**Comment by abhi5691** [comment]
Hello @konradst  could you solve this?

My configuration is precisely same as @konradst and I also incorporated the changes in PR#2997 shared by @fpasch , rebuilt the simulator, but got the same blast of errors as shared above

I also tried to follow @fpasch 's suggestion of using current master but then I no longer get egg file for Python2, which is necessary for me as I am using ros-bridge. Can someone suggest what can be at the root of this issue?

**Comment by konradst** [comment]
@abhi5691 I only suppressed the error with 2>/dev/null for the console's relief ;) and forgot about the issue. I'm waiting for ros noetic bridge to happen.

**Comment by fpasch** [comment]
@konradst noetic bridge was just merged.
