### ISSUE TITLE
Error running ros bridge example

### ISSUE THREAD

**Issue by pringithub** [carla-simulator/ros-bridge#339]
Ubuntu 18.04 
ROS Melodic
CARLA 0.9.9
Python 2.7.17
pygame 1.9.1

Hello,

I can't get a display to show up through pygame. Essentially I'm getting blank screen in the pygame client. The topics are populated, as rqt_image_view shows the images just fine. 

Anyone else having this issue? I'm not sure if this is a pygame issue or not...

[ERROR] [1595633461.991837, 117.067078]: bad callback: <bound method World.on_view_image of <__main__.World object at 0x7f3ab5a90410>>                                                [105/3726]
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/opt/carla-ros-bridge/melodic/lib/carla_manual_control/carla_manual_control.py", line 130, in on_view_image
    self._surface = pygame.surfarray.make_surface(array.swapaxes(0, 1))
  File "/usr/lib/python2.7/dist-packages/pygame/surfarray.py", line 243, in make_surface
    return numpysf.make_surface (array)
  File "/usr/lib/python2.7/dist-packages/pygame/_numpysurfarray.py", line 368, in make_surface
    blit_array (surface, array)
  File "/usr/lib/python2.7/dist-packages/pygame/_numpysurfarray.py", line 437, in blit_array
    surface.get_buffer ().write (data, 0)
IndexError: bytes to write exceed buffer size

**Comment by fpasch** [comment]
Could you please try it again with pygame version 1.9.6?
