### ISSUE TITLE
Error: map not found

### ISSUE THREAD

**Issue by SandyWare** [carla-simulator/ros-bridge#609]
**Environment :**
Ubuntu 18.0.4
Carla version (tag: 0.9.13) latest.
Ros_bridge : latest

I have build ros_bridge successfully using catkin_make.
Then ros_bridge launched using
  roslaunch carla_ros_bridge carla_ros_bridge.launch

Then I got the below error :
      **Error: map not found**

```
started core service [/rosout]
process[carla_ros_bridge-2]: started with pid [28659]
[INFO] [1648443272.634658, 0.000000]: Trying to connect to localhost:2000
[INFO] [1648443273.038154, 0.000000]: Loading town 'Town01' (previous: 'Carla/Maps/Town10HD_Opt').
[ERROR] [1648443273.119173, 0.000000]: Error: map not found
[INFO] [1648443273.121321, 0.000000]: Shutting down...
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/core.py", line 572, in signal_shutdown
    h()
  File "/home/ubuntu/carla-ros-bridge/catkin_ws/src/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/bridge.py", line 350, in destroy
    self.shutdown.set()

```
Any suggestion what I am doing wrong?

**Comment by Jk7913** [comment]
Might be that servers needs some time in order to load the map. Try launching again after the new map has been loaded.
