### ISSUE TITLE
[0.9.11]error in ubuntu20.04 with ros-bridge 

### ISSUE THREAD

**Issue by badaolaziang** [carla-simulator/ros-bridge#649]
Dear carla community, I have the conda python=3.7 environment and ROS Noetic in my Ubuntu 20.04,
when I launch the Carla 0.9.11 and try to **roslaunch carla_ros_bridge carla_ros_bridge_with_example_ego_vehicle.launch** , I get the following:

> ... logging to /home/zza/.ros/log/f3c3a116-6fe6-11ed-8f37-4f899b1493fc/roslaunch-zza-LEGION-REN9000K-34IRZ-88779.log
> Checking log directory for disk usage. This may take a while.
> Press Ctrl-C to interrupt
> Done checking log file disk usage. Usage is <1GB.
> 
> started roslaunch server http://zza-LEGION-REN9000K-34IRZ:33811/
> 
> SUMMARY
> ========
> 
> PARAMETERS
>  * /carla_manual_control_ego_vehicle/role_name: ego_vehicle
>  * /carla_ros_bridge/ego_vehicle_role_name: ["hero", "ego_veh...
>  * /carla_ros_bridge/fixed_delta_seconds: 0.05
>  * /carla_ros_bridge/host: localhost
>  * /carla_ros_bridge/passive: 
>  * /carla_ros_bridge/port: 2000
>  * /carla_ros_bridge/register_all_sensors: True
>  * /carla_ros_bridge/synchronous_mode: True
>  * /carla_ros_bridge/synchronous_mode_wait_for_vehicle_control_command: False
>  * /carla_ros_bridge/timeout: 10
>  * /carla_ros_bridge/town: 
>  * /carla_spawn_objects_zza_LEGION_REN9000K_34IRZ_88779_245486855327607148/objects_definition_file: /home/zza/catkin_...
>  * /carla_spawn_objects_zza_LEGION_REN9000K_34IRZ_88779_245486855327607148/spawn_point_ego_vehicle: 
>  * /carla_spawn_objects_zza_LEGION_REN9000K_34IRZ_88779_245486855327607148/spawn_sensors_only: False
>  * /rosdistro: noetic
>  * /rosversion: 1.15.14
>  * /set_initial_pose_ego_vehicle/control_id: control
>  * /set_initial_pose_ego_vehicle/role_name: ego_vehicle
>  * /use_sim_time: True
> 
> NODES
>   /
>     carla_manual_control_ego_vehicle (carla_manual_control/carla_manual_control.py)
>     carla_ros_bridge (carla_ros_bridge/bridge.py)
>     carla_spawn_objects_zza_LEGION_REN9000K_34IRZ_88779_245486855327607148 (carla_spawn_objects/carla_spawn_objects.py)
>     set_initial_pose_ego_vehicle (carla_spawn_objects/set_initial_pose.py)
> 
> auto-starting new master
> process[master]: started with pid [88847]
> ROS_MASTER_URI=http://localhost:11311
> 
> setting /run_id to f3c3a116-6fe6-11ed-8f37-4f899b1493fc
> process[rosout-1]: started with pid [88903]
> started core service [/rosout]
> process[carla_ros_bridge-2]: started with pid [88910]
> process[carla_spawn_objects_zza_LEGION_REN9000K_34IRZ_88779_245486855327607148-3]: started with pid [88911]
> process[set_initial_pose_ego_vehicle-4]: started with pid [88912]
> process[carla_manual_control_ego_vehicle-5]: started with pid [88913]
> pygame 2.1.2 (SDL 2.0.16, Python 3.7.15)
> Hello from the pygame community. https://www.pygame.org/contribute.html
> [INFO] [1669727325.390611, 0.000000]: Trying to connect to localhost:2000
> /home/zza/catkin_gpir/src/gpir/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/bridge.py:416: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
>   if LooseVersion(dist.version) != LooseVersion(CarlaRosBridge.CARLA_VERSION):
> /home/zza/catkin_gpir/src/gpir/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/bridge.py:421: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
>   if LooseVersion(carla_client.get_server_version()) != \
> /home/zza/catkin_gpir/src/gpir/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/bridge.py:422: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
>   LooseVersion(carla_client.get_client_version()):
> [INFO] [1669727325.543054, 0.000000]: Loading town '' (previous: 'OpenDriveMap').
> [INFO] [1669727326.195059, 0.000000]: synchronous_mode: True
> [INFO] [1669727326.195896, 0.000000]: fixed_delta_seconds: 0.05
> [INFO] [1669727326.204063, 0.000000]: Parameters:
> [INFO] [1669727326.204794, 0.000000]:   host: localhost
> [INFO] [1669727326.205450, 0.000000]:   port: 2000
> [INFO] [1669727326.206023, 0.000000]:   timeout: 10
> [INFO] [1669727326.206533, 0.000000]:   passive: 
> [INFO] [1669727326.206991, 0.000000]:   synchronous_mode: True
> [INFO] [1669727326.207446, 0.000000]:   synchronous_mode_wait_for_vehicle_control_command: False
> [INFO] [1669727326.207914, 0.000000]:   fixed_delta_seconds: 0.05
> [INFO] [1669727326.208376, 0.000000]:   register_all_sensors: True
> [INFO] [1669727326.208815, 0.000000]:   town: 
> [INFO] [1669727326.209251, 0.000000]:   ego_vehicle: {'role_name': '["hero", "ego_vehicle", "hero0", "hero1", "hero2", "hero3", "hero4", "hero5", "hero6", "hero7", "hero8", "hero9"]'}
> [INFO] [1669727326.364266, 0.000000]: Created TrafficLight(id=256)
> [INFO] [1669727326.365478, 0.000000]: Created TrafficLight(id=257)
> [INFO] [1669727326.368570, 0.000000]: Created TrafficLight(id=258)
> [INFO] [1669727326.369405, 0.000000]: Created TrafficLight(id=259)
> [INFO] [1669727326.369748, 0.000000]: Created TrafficLight(id=260)
> [INFO] [1669727326.370055, 0.000000]: Created TrafficLight(id=261)
> [INFO] [1669727326.370349, 0.000000]: Created TrafficLight(id=262)
> [INFO] [1669727326.370633, 0.000000]: Created TrafficLight(id=263)
> [INFO] [1669727326.370945, 0.000000]: Created TrafficLight(id=264)
> [INFO] [1669727326.371260, 0.000000]: Created TrafficLight(id=265)
> [INFO] [1669727326.371561, 0.000000]: Created TrafficLight(id=266)
> [INFO] [1669727326.371991, 0.000000]: Created TrafficLight(id=267)
> [INFO] [1669727326.372363, 0.000000]: Created TrafficLight(id=268)
> [INFO] [1669727326.372728, 0.000000]: Created TrafficLight(id=269)
> [INFO] [1669727326.373083, 0.000000]: Created TrafficLight(id=270)
> [INFO] [1669727326.373458, 0.000000]: Created TrafficLight(id=271)
> [INFO] [1669727326.373821, 0.000000]: Created TrafficLight(id=272)
> [INFO] [1669727326.374180, 0.000000]: Created TrafficLight(id=273)
> [INFO] [1669727326.374537, 0.000000]: Created Spectator(id=214)
> [INFO] [1669727326.374897, 0.000000]: Created Traffic(id=215)
> [INFO] [1669727326.375269, 0.000000]: Created Traffic(id=216)
> [INFO] [1669727326.375633, 0.000000]: Created Traffic(id=217)
> [INFO] [1669727326.375995, 0.000000]: Created Traffic(id=218)
> [INFO] [1669727326.376352, 0.000000]: Created Traffic(id=219)
> [INFO] [1669727326.376704, 0.000000]: Created TrafficLight(id=220)
> [INFO] [1669727326.377075, 0.000000]: Created TrafficLight(id=221)
> [INFO] [1669727326.377443, 0.000000]: Created TrafficLight(id=222)
> [INFO] [1669727326.377799, 0.000000]: Created TrafficLight(id=223)
> [INFO] [1669727326.378148, 0.000000]: Created TrafficLight(id=224)
> [INFO] [1669727326.378494, 0.000000]: Created TrafficLight(id=225)
> [INFO] [1669727326.378835, 0.000000]: Created TrafficLight(id=226)
> [INFO] [1669727326.379196, 0.000000]: Created TrafficLight(id=227)
> [INFO] [1669727326.379550, 0.000000]: Created TrafficLight(id=228)
> [INFO] [1669727326.379914, 0.000000]: Created TrafficLight(id=229)
> [INFO] [1669727326.380265, 0.000000]: Created TrafficLight(id=230)
> [INFO] [1669727326.380630, 0.000000]: Created TrafficLight(id=231)
> [INFO] [1669727326.380981, 0.000000]: Created TrafficLight(id=232)
> [INFO] [1669727326.381345, 0.000000]: Created TrafficLight(id=233)
> [INFO] [1669727326.381714, 0.000000]: Created TrafficLight(id=234)
> [INFO] [1669727326.382078, 0.000000]: Created TrafficLight(id=235)
> [INFO] [1669727326.382438, 0.000000]: Created TrafficLight(id=236)
> [INFO] [1669727326.382827, 0.000000]: Created TrafficLight(id=237)
> [INFO] [1669727326.383384, 0.000000]: Created TrafficLight(id=238)
> [INFO] [1669727326.383790, 0.000000]: Created TrafficLight(id=239)
> [INFO] [1669727326.384191, 0.000000]: Created TrafficLight(id=240)
> [INFO] [1669727326.384517, 0.000000]: Created TrafficLight(id=241)
> [INFO] [1669727326.384820, 0.000000]: Created TrafficLight(id=242)
> [INFO] [1669727326.385113, 0.000000]: Created TrafficLight(id=243)
> [INFO] [1669727326.385424, 0.000000]: Created TrafficLight(id=244)
> [INFO] [1669727326.385726, 0.000000]: Created TrafficLight(id=245)
> [INFO] [1669727326.386012, 0.000000]: Created TrafficLight(id=246)
> [INFO] [1669727326.386286, 0.000000]: Created TrafficLight(id=247)
> [INFO] [1669727326.386557, 0.000000]: Created TrafficLight(id=248)
> [INFO] [1669727326.386826, 0.000000]: Created TrafficLight(id=249)
> [INFO] [1669727326.387094, 0.000000]: Created TrafficLight(id=250)
> [INFO] [1669727326.387382, 0.000000]: Created TrafficLight(id=251)
> [INFO] [1669727326.387677, 0.000000]: Created TrafficLight(id=252)
> [INFO] [1669727326.387961, 0.000000]: Created TrafficLight(id=253)
> [INFO] [1669727326.388241, 0.000000]: Created TrafficLight(id=254)
> [INFO] [1669727326.388507, 0.000000]: Created TrafficLight(id=255)
> [INFO] [1669727326.534511, 3.051635]: Object (type='sensor.pseudo.traffic_lights', id='traffic_lights') spawned successfully as 10000.
> [INFO] [1669727326.535729, 3.051635]: Object (type='sensor.pseudo.objects', id='objects') spawned successfully as 10001.
> [INFO] [1669727326.537017, 3.101635]: Created TrafficLightsSensor(id=10000)
> [INFO] [1669727326.537635, 3.101635]: Created ObjectSensor(id=10001)
> [INFO] [1669727326.537999, 3.101635]: Object (type='sensor.pseudo.actor_list', id='actor_list') spawned successfully as 10002.
> [INFO] [1669727326.540212, 3.151635]: Created ActorListSensor(id=10002)
> [INFO] [1669727326.540738, 3.151635]: Object (type='sensor.pseudo.markers', id='markers') spawned successfully as 10003.
> [INFO] [1669727326.541922, 3.151635]: Object (type='sensor.pseudo.opendrive_map', id='map') spawned successfully as 10004.
> [WARN] [1669727326.542675, 3.151635]: Invalid spawnpoint ''
> [WARN] [1669727326.543142, 3.201635]: ego_vehicle: Could not use spawn point from parameters, the spawn point from config file will be used.
> [INFO] [1669727326.543540, 3.201635]: Spawn point selected at random
> [INFO] [1669727326.556278, 3.201635]: Created MarkerSensor(id=10003)
> [INFO] [1669727326.641768, 3.201635]: Created OpenDriveSensor(id=10004)
> [INFO] [1669727326.645373, 3.251635]: Object (type='vehicle.tesla.model3', id='ego_vehicle') spawned successfully as 274.
> [INFO] [1669727326.648213, 3.251635]: Created EgoVehicle(id=274)
> [INFO] [1669727326.649971, 3.301635]: Object (type='sensor.camera.rgb', id='rgb_front') spawned successfully as 275.
> [INFO] [1669727326.651307, 3.301635]: Created RgbCamera(id=275)
> [INFO] [1669727326.659831, 3.351635]: Object (type='sensor.camera.rgb', id='rgb_view') spawned successfully as 276.
> Exception in thread Thread-7:
> Traceback (most recent call last):
>   File "/home/zza/miniconda3/envs/carla_py37/lib/python3.7/threading.py", line 926, in _bootstrap_inner
>     self.run()
>   File "/home/zza/miniconda3/envs/carla_py37/lib/python3.7/threading.py", line 870, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/zza/catkin_gpir/src/gpir/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/bridge.py", line 274, in _synchronous_mode_update
>     self._update(frame, world_snapshot.timestamp.elapsed_seconds)
>   File "/home/zza/catkin_gpir/src/gpir/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/bridge.py", line 314, in _update
>     self.actor_factory.update_actor_states(frame_id, timestamp)
>   File "/home/zza/catkin_gpir/src/gpir/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/actor_factory.py", line 143, in update_actor_states
>     self.actors[actor_id].update(frame_id, timestamp)
>   File "/home/zza/catkin_gpir/src/gpir/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/sensor.py", line 253, in update
>     self._update_synchronous_sensor(frame, timestamp)
>   File "/home/zza/catkin_gpir/src/gpir/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/sensor.py", line 234, in _update_synchronous_sensor
>     self.sensor_data_updated(carla_sensor_data)
>   File "/home/zza/catkin_gpir/src/gpir/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/camera.py", line 121, in sensor_data_updated
>     img_msg = self.get_ros_image(carla_camera_data)
>   File "/home/zza/catkin_gpir/src/gpir/ros-bridge/carla_ros_bridge/src/carla_ros_bridge/camera.py", line 163, in get_ros_image
>     img_msg = Camera.cv_bridge.cv2_to_imgmsg(image_data_array, encoding=encoding)
>   File "/opt/ros/noetic/lib/python3/dist-packages/cv_bridge/core.py", line 266, in cv2_to_imgmsg
>     if self.cvtype_to_name[self.encoding_to_cvtype2(encoding)] != cv_type:
>   File "/opt/ros/noetic/lib/python3/dist-packages/cv_bridge/core.py", line 91, in encoding_to_cvtype2
>     from cv_bridge.boost.cv_bridge_boost import getCvType
> **ImportError: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined symbol: ffi_type_pointer, version LIBFFI_BASE_7.0**
> [INFO] [1669727326.665187, 3.351635]: Object (type='actor.pseudo.control', id='control') spawned successfully as 10005.
> 
> [INFO] [1669727326.666708, 3.351635]: Object (type='sensor.lidar.ray_cast', id='lidar') spawned successfully as 277.
> [INFO] [1669727326.667937, 3.351635]: Object (type='sensor.lidar.ray_cast_semantic', id='semantic_lidar') spawned successfully as 278.
> [INFO] [1669727326.668973, 3.351635]: Object (type='sensor.other.radar', id='radar_front') spawned successfully as 279.
> [INFO] [1669727326.670466, 3.351635]: Object (type='sensor.camera.semantic_segmentation', id='semantic_segmentation_front') spawned successfully as 280.
> [INFO] [1669727326.671913, 3.351635]: Object (type='sensor.camera.depth', id='depth_front') spawned successfully as 281.
> [INFO] [1669727326.673321, 3.351635]: Object (type='sensor.camera.dvs', id='dvs_front') spawned successfully as 282.
> [INFO] [1669727326.674395, 3.351635]: Object (type='sensor.other.gnss', id='gnss') spawned successfully as 283.
> [INFO] [1669727326.675409, 3.351635]: Object (type='sensor.other.imu', id='imu') spawned successfully as 284.
> [INFO] [1669727326.676454, 3.351635]: Object (type='sensor.other.collision', id='collision') spawned successfully as 285.
> [INFO] [1669727326.677399, 3.351635]: Object (type='sensor.other.lane_invasion', id='lane_invasion') spawned successfully as 286.
> [INFO] [1669727326.678196, 3.351635]: Object (type='sensor.pseudo.tf', id='tf') spawned successfully as 10006.
> [INFO] [1669727326.678977, 3.351635]: Object (type='sensor.pseudo.objects', id='objects') spawned successfully as 10007.
> [INFO] [1669727326.679716, 3.351635]: Object (type='sensor.pseudo.odom', id='odometry') spawned successfully as 10008.
> [INFO] [1669727326.680459, 3.351635]: Object (type='sensor.pseudo.speedometer', id='speedometer') spawned successfully as 10009.
> [INFO] [1669727326.681197, 3.351635]: Object (type='actor.pseudo.control', id='control') spawned successfully as 10010.
> [INFO] [1669727326.681479, 3.351635]: All objects spawned.

It seems that something is wrong between the ros cv_bridge or else. 
And the corresponding Carla ros manual control window shows as follows, the frame stops and would not add:
![Screenshot 2022-11-29 22:15:11](https://user-images.githubusercontent.com/31429829/204553151-60acff19-bb11-42b5-92e3-0bbcb0da1dcb.png)

Hope there are some suggestions~Best wishes.

**Comment by badaolaziang** [comment]
Solved, I re-catkin_make the ros-bridge with python3.8 and successfully run the bridge.
