### ISSUE TITLE
I install and run the Tutorial but am

### ISSUE THREAD

**Issue by ahmet-f-gumustas** [carla-simulator/ros-bridge#735]
Hey guys;

I am taking a some errors . I read and applied this tutorial   'https://learnopencv.com/ros2-and-carla-setup-guide/'

terminal 1 : ros2 launch carla_ros_bridge carla_ros_bridge.launch.py synchronous_mode:=True town:=Town03
terminal 2 : ros2 launch carla_spawn_objects carla_example_ego_vehicle.launch.py spawn_sensors_only:=False objects_definition_file:=/home/moveon2/carla-ros-bridge/catkin_ws/src/carla_ros/carla_spawn_objects/config/objects.json

and gave me a terminal 1 errors 

[bridge-1] [WARN] [1720124551.325446457] [carla_ros_bridge]: DVSCamera(117): Received event for frame 5966 (expected 5967). Process it anyways.
[bridge-1] /home/moveon2/carla-ros-bridge/catkin_ws/install/carla_ros_bridge/lib/python3.10/site-packages/carla_ros_bridge/camera.py:455: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
[bridge-1]   ('pol', numpy.bool)
[bridge-1] Exception in thread Thread-2 (_synchronous_mode_update):
[bridge-1] Traceback (most recent call last):
[bridge-1]   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
[bridge-1]     self.run()
[bridge-1]   File "/usr/lib/python3.10/threading.py", line 953, in run
[bridge-1]     self._target(*self._args, **self._kwargs)
[bridge-1]   File "/home/moveon2/carla-ros-bridge/catkin_ws/install/carla_ros_bridge/lib/python3.10/site-packages/carla_ros_bridge/bridge.py", line 274, in _synchronous_mode_update
[bridge-1]     self._update(frame, world_snapshot.timestamp.elapsed_seconds)
[bridge-1]   File "/home/moveon2/carla-ros-bridge/catkin_ws/install/carla_ros_bridge/lib/python3.10/site-packages/carla_ros_bridge/bridge.py", line 314, in _update
[bridge-1]     self.actor_factory.update_actor_states(frame_id, timestamp)
[bridge-1]   File "/home/moveon2/carla-ros-bridge/catkin_ws/install/carla_ros_bridge/lib/python3.10/site-packages/carla_ros_bridge/actor_factory.py", line 143, in update_actor_states
[bridge-1]     self.actors[actor_id].update(frame_id, timestamp)
[bridge-1]   File "/home/moveon2/carla-ros-bridge/catkin_ws/install/carla_ros_bridge/lib/python3.10/site-packages/carla_ros_bridge/sensor.py", line 251, in update
[bridge-1]     self._update_synchronous_event_sensor(frame, timestamp)
[bridge-1]   File "/home/moveon2/carla-ros-bridge/catkin_ws/install/carla_ros_bridge/lib/python3.10/site-packages/carla_ros_bridge/sensor.py", line 217, in _update_synchronous_event_sensor
[bridge-1]     self.sensor_data_updated(carla_sensor_data)
[bridge-1]   File "/home/moveon2/carla-ros-bridge/catkin_ws/install/carla_ros_bridge/lib/python3.10/site-packages/carla_ros_bridge/camera.py", line 424, in sensor_data_updated
[bridge-1]     super(DVSCamera, self).sensor_data_updated(carla_dvs_event_array)
[bridge-1]   File "/home/moveon2/carla-ros-bridge/catkin_ws/install/carla_ros_bridge/lib/python3.10/site-packages/carla_ros_bridge/camera.py", line 121, in sensor_data_updated
[bridge-1]     img_msg = self.get_ros_image(carla_camera_data)
[bridge-1]   File "/home/moveon2/carla-ros-bridge/catkin_ws/install/carla_ros_bridge/lib/python3.10/site-packages/carla_ros_bridge/camera.py", line 161, in get_ros_image
[bridge-1]     image_data_array, encoding = self.get_carla_image_data_array(
[bridge-1]   File "/home/moveon2/carla-ros-bridge/catkin_ws/install/carla_ros_bridge/lib/python3.10/site-packages/carla_ros_bridge/camera.py", line 455, in get_carla_image_data_array
[bridge-1]     ('pol', numpy.bool)
[bridge-1]   File "/home/moveon2/.local/lib/python3.10/site-packages/numpy/__init__.py", line 305, in __getattr__
[bridge-1]     raise AttributeError(__former_attrs__[attr])
[bridge-1] AttributeError: module 'numpy' has no attribute 'bool'.
[bridge-1] `np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
[bridge-1] The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
[bridge-1]     https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'bool_'?

But ı dont know how to solve this . 

When you get the error on the UI side, a freeze also occurs.

**Comment by ahmet-f-gumustas** [comment]
automatic_control.py       manual_control.py                show_recorder_file_info.py
client_bounding_boxes.py   manual_control_steeringwheel.py  start_recording.py
draw_skeleton.py           no_rendering_mode.py             start_replaying.py
dynamic_weather.py         open3d_lidar.py                  synchronous_mode.py
generate_traffic.py        requirements.txt                 tutorial_gbuffer.py
lidar_to_camera.py         rss                              tutorial.py
manual_control_carsim.py   sensor_synchronization.py        vehicle_gallery.py
manual_control_chrono.py   show_recorder_actors_blocked.py  vehicle_physics.py
manual_control_gbuffer.py  show_recorder_collisions.py      visualize_multiple_sensors.py


moveon2asus-tuf:~/carla_simulator/PythonAPI/examples$ python3 generate_traffic.py 
Segmentation fault (core dumped)

**Comment by mustafa-onur-kilinc** [comment]
> Hey guys;
> 
> I am taking a some errors . I read and applied this tutorial 'https://learnopencv.com/ros2-and-carla-setup-guide/'
> 
> terminal 1 : ros2 launch carla_ros_bridge carla_ros_bridge.launch.py synchronous_mode:=True town:=Town03 terminal 2 : ros2 launch carla_spawn_objects carla_example_ego_vehicle.launch.py spawn_sensors_only:=False objects_definition_file:=/home/moveon2/carla-ros-bridge/catkin_ws/src/carla_ros/carla_spawn_objects/config/objects.json
> 
> and gave me a terminal 1 errors
> 
> [bridge-1] [WARN] [1720124551.325446457] [carla_ros_bridge]: DVSCamera(117): Received event for frame 5966 (expected 5967). Process it anyways. [bridge-1] /home/moveon2/carla-ros-bridge/catkin_ws/install/carla_ros_bridge/lib/python3.10/site-packages/carla_ros_bridge/camera.py:455: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar. [bridge-1] ('pol', numpy.bool) [bridge-1] Exception in thread Thread-2 (_synchronous_mode_update): [bridge-1] Traceback (most recent call last): [bridge-1] File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner [bridge-1] self.run() [bridge-1] File "/usr/lib/python3.10/threading.py", line 953, in run [bridge-1] self._target(*self._args, **self._kwargs) [bridge-1] File "/home/moveon2/carla-ros-bridge/catkin_ws/install/carla_ros_bridge/lib/python3.10/site-packages/carla_ros_bridge/bridge.py", line 274, in _synchronous_mode_update [bridge-1] self._update(frame, world_snapshot.timestamp.elapsed_seconds) [bridge-1] File "/home/moveon2/carla-ros-bridge/catkin_ws/install/carla_ros_bridge/lib/python3.10/site-packages/carla_ros_bridge/bridge.py", line 314, in _update [bridge-1] self.actor_factory.update_actor_states(frame_id, timestamp) [bridge-1] File "/home/moveon2/carla-ros-bridge/catkin_ws/install/carla_ros_bridge/lib/python3.10/site-packages/carla_ros_bridge/actor_factory.py", line 143, in update_actor_states [bridge-1] self.actors[actor_id].update(frame_id, timestamp) [bridge-1] File "/home/moveon2/carla-ros-bridge/catkin_ws/install/carla_ros_bridge/lib/python3.10/site-packages/carla_ros_bridge/sensor.py", line 251, in update [bridge-1] self._update_synchronous_event_sensor(frame, timestamp) [bridge-1] File "/home/moveon2/carla-ros-bridge/catkin_ws/install/carla_ros_bridge/lib/python3.10/site-packages/carla_ros_bridge/sensor.py", line 217, in _update_synchronous_event_sensor [bridge-1] self.sensor_data_updated(carla_sensor_data) [bridge-1] File "/home/moveon2/carla-ros-bridge/catkin_ws/install/carla_ros_bridge/lib/python3.10/site-packages/carla_ros_bridge/camera.py", line 424, in sensor_data_updated [bridge-1] super(DVSCamera, self).sensor_data_updated(carla_dvs_event_array) [bridge-1] File "/home/moveon2/carla-ros-bridge/catkin_ws/install/carla_ros_bridge/lib/python3.10/site-packages/carla_ros_bridge/camera.py", line 121, in sensor_data_updated [bridge-1] img_msg = self.get_ros_image(carla_camera_data) [bridge-1] File "/home/moveon2/carla-ros-bridge/catkin_ws/install/carla_ros_bridge/lib/python3.10/site-packages/carla_ros_bridge/camera.py", line 161, in get_ros_image [bridge-1] image_data_array, encoding = self.get_carla_image_data_array( [bridge-1] File "/home/moveon2/carla-ros-bridge/catkin_ws/install/carla_ros_bridge/lib/python3.10/site-packages/carla_ros_bridge/camera.py", line 455, in get_carla_image_data_array [bridge-1] ('pol', numpy.bool) [bridge-1] File "/home/moveon2/.local/lib/python3.10/site-packages/numpy/**init**.py", line 305, in **getattr** [bridge-1] raise AttributeError(**former_attrs**[attr]) [bridge-1] AttributeError: module 'numpy' has no attribute 'bool'. [bridge-1] `np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here. [bridge-1] The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at: [bridge-1] https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'bool_'?
> 
> But ı dont know how to solve this .
> 
> When you get the error on the UI side, a freeze also occurs.

I have followed the same tutorial and got the same error.

Changing line 455 in /home/\<username\>/carla-ros-bridge/catkin_ws/src/carla_ros/carla_ros_bridge/src/carla_ros_bridge/camera.py file from "('pol', numpy.bool)" to "('pol', bool)" has solved my problem and I can get the intended outputs in Rviz.
